[package]
name = "osm-maxspeed"
version = "0.0.1"
authors = [ "Felix Buehler <account@buehler.rocks>" ]
edition = "2018"

include = [
  "README.md",
  ".gitignore",
  "Cargo.toml",
  "src/*.rs"
]

[dependencies]
clap = "2.33"
osmpbfreader = "0.14"
